app/imports/startup/client/routes-config.ts, app/imports/ui/components/shared/ExplorerCoursesWidget.tsx, app/imports/ui/components/shared/ExplorerOpportunitiesWidget.tsx, app/imports/ui/components/student/StudentExplorerCoursesWidgetButton.tsx, app/imports/ui/components/student/StudentExplorerOpportunitiesWidgetButton.tsx, app/imports/ui/components/student/StudentExplorerReviewWidget.tsx, app/imports/ui/pages/shared/ExplorerCoursesPage.tsx, app/imports/ui/pages/shared/ExplorerOpportunitiesPage.tsx
Status: 🚧 
* *meteor npm run test* ❌ 
* *meteor npm run test-app* ❌ 
Closes #56 
Same exact UI bugs as #67 except for Opportunities.
=> [issue-56] - Individual Explorer Opportunities

app/imports/ui/components/shared/CardExplorerMenu.tsx, app/imports/ui/components/shared/TermCard.tsx, app/imports/ui/pages/shared/CardExplorerPage.tsx
Status: ✅ 
* *meteor npm run test* 👌  
* *meteor npm run test-app* 👌 
Creates the Card Explorer Menu part of #63. Was planning on finishing #69 first before moving on to create the Individual Explorer Menu of #63 
N/A
=> [issue-63] - Card Explorer Menu

app/.meteor/versions, app/imports/startup/client/routes-config.ts, app/imports/ui/components/shared/ExplorerConstants.ts, app/imports/ui/components/shared/ProfileAdd.tsx, app/imports/ui/components/shared/RouterHelperFunctions.ts, app/imports/ui/components/student/StudentMentorSpaceQuestionsAccordion.tsx, app/imports/ui/pages/shared/CardExplorerPage.tsx, app/imports/ui/pages/shared/ExplorerCoursesPage.tsx, app/imports/ui/pages/shared/IndividualExplorerPage.tsx
Status: 🚧 
* *meteor npm run test* 👌 
* *meteor npm run test-app* ❌ 
Closes #78 
N/A
=> [issue-78] - Refactor routes-config.ts to use constants

app/imports/ui/components/landing/LandingPlanChoicePill.tsx, app/imports/ui/components/shared/AcademicPlanStaticTermView.tsx, app/imports/ui/components/shared/AcademicPlanStaticViewer.tsx, app/imports/ui/components/shared/AcademicPlanStaticYearView.tsx, app/imports/ui/components/shared/AcademicPlanTermView.tsx, app/imports/ui/components/shared/DraggablePlanChoicePill.tsx, app/imports/ui/components/shared/ExplorerPlansWidget.tsx, app/imports/ui/components/shared/PlanCard.tsx, app/imports/ui/components/shared/SatisfiedPlanChoicePill.tsx, app/imports/ui/components/shared/StaticPlanChoicePill.tsx, app/imports/ui/components/shared/StyleFunctions.ts
Status: 🚧 
When I first did Academic Plan Explorers, I used the Draggable components that are already built. This refactor makes it so I have my own static components.
N/A
=> [issue-51] - Refactored Academic Plan Explorer

app/imports/startup/client/routes-config.ts, app/imports/ui/components/landing/LandingAcademicTermView.tsx, app/imports/ui/components/landing/LandingPlanChoicePill.tsx, app/imports/ui/components/shared/AcademicPlanStaticTermView.tsx, app/imports/ui/components/shared/AcademicPlanTermView.tsx, app/imports/ui/components/shared/CardExplorerMenu.tsx, app/imports/ui/components/shared/CardExplorerWidget.tsx, app/imports/ui/components/shared/ExplorerCard.tsx, app/imports/ui/components/shared/ExplorerCareerGoalsWidget.tsx, app/imports/ui/components/shared/ExplorerCoursesWidget.tsx, app/imports/ui/components/shared/ExplorerInterestsWidget.tsx, app/imports/ui/components/shared/ExplorerNavDropdown.tsx, app/imports/ui/components/shared/ExplorerOpportunitiesWidget.tsx, app/imports/ui/components/shared/ExplorerPlansWidget.tsx, app/imports/ui/components/shared/InterestList.tsx, app/imports/ui/components/shared/InterestedProfilesWidget.tsx, app/imports/ui/components/shared/InterestedRelatedWidget.tsx, app/imports/ui/components/shared/PlanCard.tsx, app/imports/ui/components/shared/ProfileAdd.tsx, app/imports/ui/components/shared/ProfileCard.tsx, app/imports/ui/components/shared/SatisfiedPlanChoicePill.tsx, app/imports/ui/components/shared/StaticPlanChoicePill.tsx, app/imports/ui/components/shared/TermCard.tsx, app/imports/ui/pages/shared/CardExplorerPage.tsx, app/imports/ui/pages/shared/ExplorerHomePage.tsx, app/imports/ui/pages/shared/IndividualExplorerPage.tsx
Status: 🚧 
Closes #81 
Since this is a big refactor, make sure nothing got broken.
=> [issue-81] Refactor Card Explorer and Individual Explorer to use EXPLORER_TYPE and URL_ROLES constants

app/imports/ui/layouts/shared/InstanceSubscriptionsHOC.tsx
Construction: ✅ 
Closes #98 
N/A
=> [issue-98] Improved load time for students

app/.eslintrc, app/imports/api/course/CourseUtilities.ts, app/imports/api/degree-plan/PlanChoiceUtilities.ts, app/imports/startup/client/routes-config.ts, app/imports/typings/radgrad.d.ts, app/imports/ui/components/shared/CardExplorerWidget.tsx, app/imports/ui/components/shared/ProfileCard.tsx, app/imports/ui/components/student/CoursePrerequisitesView.tsx, app/imports/ui/components/student/InspectorCourseMenu.tsx, app/imports/ui/components/student/StudentAboutMeUpdatePictureForm.tsx, app/imports/ui/components/student/StudentAboutMeUpdateWebsiteForm.tsx, app/imports/ui/components/student/StudentAboutMeWidget.tsx, app/imports/ui/components/student/StudentHomeMenu.tsx, app/imports/ui/components/student/StudentIceColumn.tsx, app/imports/ui/components/student/StudentIceColumnRecommended.tsx, app/imports/ui/components/student/StudentIceColumnUnverified.tsx, app/imports/ui/components/student/StudentIceColumnVerified.tsx, app/imports/ui/components/student/StudentIceWidget.tsx, app/imports/ui/components/student/StudentLevelsOthersWidget.tsx, app/imports/ui/components/student/StudentLevelsWidget.tsx, app/imports/ui/components/student/StudentLogWidget.tsx, app/imports/ui/components/student/StudentMentorSpaceQuestionForm.tsx, app/imports/ui/components/student/StudentOfInterestWidget.tsx, app/imports/ui/components/student/StudentShareInfoWidget.tsx, app/imports/ui/pages/student/StudentHomeAboutMePage.tsx, app/imports/ui/pages/student/StudentHomeIcePage.tsx, app/imports/ui/pages/student/StudentHomeLevelsPage.tsx, app/imports/ui/pages/student/StudentHomeLogPage.tsx, app/imports/ui/pages/student/StudentMentorSpacePage.tsx
=> [issue-107] Student Home About Me, ICE Points, Levels, and Advisor Log Pages

app/private/database/quarter/2018-12-27-09-06-31.json, app/private/database/snapshot/2018-12-10-11-05-40.json, config/settings.development.json
=> [issue-114] Add students to the semester fixture

app/imports/ui/components/shared/CardExplorerMenu.tsx, app/imports/ui/components/shared/MenuIceCircle.tsx, app/imports/ui/components/shared/RadGradMenuProfile.tsx, app/imports/ui/components/shared/UserProfileCard.tsx
Status: ✅ :
Fixes the two UI issues from https://github.com/radgrad/radgrad2/issues/94#issuecomment-511629599
N/A
=> [issue-94] - RadGradMenuProfile is now reactive and points to ICE Page

app/imports/ui/components/mentor/MentorMentorSpaceAnswerForm.tsx, app/imports/ui/components/mentor/MentorMentorSpaceQuestionsAccordion.tsx, app/imports/ui/components/shared/ExplorerUsersWidget.tsx, app/imports/ui/components/shared/UserAnswersComponent.tsx, app/imports/ui/components/student/MentorQuestionAnswerWidget.tsx, app/imports/ui/components/student/StudentMentorSpaceMentorDirectoryAccordion.tsx, app/imports/ui/components/student/StudentMentorSpaceQuestionsAccordion.tsx
=> [issue-180] Fix UI Issues for MentorSpace Pages

app/imports/ui/components/mentor/MentorMentorSpaceAnswerForm.tsx
=> [issue-181] Confirm Dialog for deleting Mentor Answers

app/imports/api/level/LevelProcessor.ts, app/imports/ui/components/shared/WidgetHeaderNumber.tsx, app/imports/ui/components/student/StudentFeedWidget.tsx, app/imports/ui/components/student/StudentOfInterestCard.tsx, app/imports/ui/components/student/StudentOfInterestWidget.tsx, app/imports/ui/components/student/StudentTeaserWidget.tsx
Status: :construction:
Closes #177
Fixes any UI issues with the Home Pages for Students, Faculty, and Mentor.
For Students, this includes the About Me, ICE Points, Levels, and Advisor Log pages.
N/A
=> [issue-177] Fixes UI Issues for Home Pages

app/imports/ui/components/landing/RadGradLoginButtons.tsx, app/imports/ui/layouts/App.tsx, app/imports/ui/pages/NotAuthorized.tsx, app/imports/ui/pages/Signin.tsx
Added NotAuthorized page.
Updated StudentProtectedRoute to check route username vs logged in username.
Status: 🎉 
Fixes #197 
=> issue-197 Students can access other student's data

app/imports/ui/components/faculty/FacultyPageAboutMeWidget.tsx, app/imports/ui/components/mentor/MentorAboutMeWidget.tsx, app/imports/ui/components/student/StudentAboutMeWidget.tsx, app/imports/ui/components/student/StudentIceColumnRecommended.tsx, app/imports/ui/components/student/StudentIceColumnUnverified.tsx, app/imports/ui/components/student/StudentIceColumnVerified.tsx, app/imports/ui/components/student/StudentIceWidget.tsx, app/imports/ui/components/student/StudentLevelsOthersWidget.tsx, app/imports/ui/components/student/StudentLevelsWidget.tsx, app/imports/ui/components/student/StudentLogWidget.tsx, app/package-lock.json, app/package.json
=> [issue-177] Fix UI Issues for Home Pages

app/imports/api/degree-plan/AcademicYearInstanceCollection.test.ts, app/imports/api/degree-plan/AcademicYearInstanceCollection.ts, app/imports/typings/radgrad.d.ts, app/imports/ui/components/shared/AcademicPlanYearView.tsx, app/imports/ui/components/shared/RemoveItWidget.tsx, app/imports/ui/components/student/AcademicPlanViewerWidget.tsx, app/imports/ui/components/student/AcademicTermView.tsx, app/imports/ui/components/student/AcademicYearView.tsx, app/imports/ui/components/student/DegreeExperiencePlannerWidget.tsx, app/imports/ui/components/student/DepDetailsWidget.tsx, app/imports/ui/components/student/DetailCourseCard.tsx, app/imports/ui/components/student/DetailOpportunityCard.tsx, app/imports/ui/components/student/FavoriteAcademicPlansWidget.tsx, app/imports/ui/components/student/FavoriteCourseCard.tsx, app/imports/ui/components/student/FavoriteCoursesWidget.tsx, app/imports/ui/components/student/FavoriteOpportunitiesWidget.tsx, app/imports/ui/components/student/FavoriteOpportunityCard.tsx, app/imports/ui/components/student/RequestVerificationForm.tsx, app/imports/ui/components/student/StudentIceColumnUnverified.tsx, app/imports/ui/components/student/StudentIceColumnVerified.tsx, app/imports/ui/components/student/TabbedFavoritesWidget.tsx, app/imports/ui/components/student/TabbedPlanInspector.tsx, app/imports/ui/components/student/VerificationRequestStatus.tsx, app/imports/ui/pages/Signout.tsx, app/imports/ui/pages/admin/AdminDataModelAcademicYearsPage.tsx, app/imports/ui/pages/student/StudentDegreePlannerPage.tsx, app/package-lock.json
=> [issue-184] Fix UI Issues for Student Degree Planner Page

app/imports/ui/components/shared/MenuIceCircle.tsx, app/imports/ui/layouts/shared/InstanceSubscriptionsHOC.tsx
The ICE Circles in the header now have a popup showing the earned/planned values.
=> Issue 196 - ICE circle popups

app/imports/ui/components/student/DegreeExperiencePlannerWidget.tsx
Made it reactive.
Added previous year button.
Fixes #216 
Fixes #239 
=> Issue 216 - Add previous academic year

app/imports/startup/both/accounts-config.ts, app/imports/ui/pages/Signout.tsx
=> [issue-235] UserInteraction for logout

app/imports/api/analytic/UserInteractionCollection.ts, app/imports/api/degree-plan/AcademicYearInstanceCollection.ts, app/imports/api/feedback/FeedbackInstanceCollection.ts, app/imports/api/slug/SlugCollection.ts
=> Issue 241 - Add indexes to large collections

app/imports/ui/components/landing/RadGradLoginButtons.tsx
=> [issue-225] Logging in with CAS now redirects to respective home pages

app/imports/api/page-tracking/PageInterestCollection.ts, app/imports/ui/components/landing/RadGradLoginButtons.tsx, app/imports/ui/layouts/App.tsx, app/imports/ui/layouts/student/PageTrackerHOC.tsx, app/imports/ui/pages/Signin.tsx, app/imports/ui/pages/Signout.tsx
Closes #224
It does this by forcing a refresh on the other tabs.
=> [issue-224] Logging out on one tab now logs out other tabs

app/imports/api/course/CourseInstanceCollection.ts, app/imports/api/degree-plan/AcademicYearInstanceCollection.ts, app/imports/api/favorite/FavoriteAcademicPlanCollection.ts, app/imports/api/favorite/FavoriteCareerGoalCollection.ts, app/imports/api/favorite/FavoriteCourseCollection.ts, app/imports/api/favorite/FavoriteInterestCollection.ts, app/imports/api/favorite/FavoriteOpportunityCollection.ts, app/imports/api/feedback/FeedbackInstanceCollection.ts, app/imports/api/log/AdvisorLogCollection.ts, app/imports/api/opportunity/OpportunityInstanceCollection.ts, app/imports/api/page-tracking/PageInterestCollection.ts, app/imports/api/verification/VerificationRequestCollection.ts
Fixes #203 
Now using _.isNil to check for undefined or null instead of !studentID.
We may need to reopen this issue if we see the stack traces again.
=> issue-203 - [object Object] stack trace.

app/imports/ui/layouts/App.tsx
Fixes #203 
Changed the App.txs routing so if Meteor.userId() is null redirect to landing page.
=> Issue 203 - Undefined user error when logged in and meteor reset.

app/package-lock.json, app/package.json
Closes #293 
See https://github.com/supasate/connected-react-router/issues/312#issuecomment-647082777
=> [issue-293] Temporary fix for "Uncaught could not find router reducer in..." error

app/imports/redux/shared/cardExplorer/actions.ts, app/imports/redux/shared/cardExplorer/index.ts, app/imports/redux/shared/cardExplorer/reducers.ts, app/imports/redux/shared/cardExplorer/types.ts, app/imports/redux/shared/index.ts, app/imports/ui/components/admin/AdminDataModelMenu.tsx, app/imports/ui/components/admin/ListCollectionWidget.tsx, app/imports/ui/components/shared/CardExplorerOpportunitiesPage/CardExplorerOpportunitiesWidget.tsx, app/imports/ui/components/shared/CardExplorersPaginationWidget.tsx, app/imports/ui/pages/shared/CardExplorerOpportunitiesPage.tsx, app/package-lock.json, app/package.json
Closes #289 
There is currently a warning that throws in the console:
`Warning: Received NaN for the `value` attribute. If this is expected, cast the value to a string.`
I believe this is an issue with semantic-ui-react itself. This warning comes from the use of Pagination, but this does not break the functionality of the pagination itself (as far as I know).
=> [issue-289] Pagination for Card Explorer Opportunities

app/imports/ui/components/shared/CardExplorerOpportunitiesPage/CardExplorerOpportunitiesWidget.tsx, app/imports/ui/components/shared/CardExplorerOpportunitiesPage/CardExplorerSummerOpportunitiesWidget.tsx, app/imports/ui/components/shared/CardExplorerOpportunitiesPage/OpportunityInformationItem.tsx, app/imports/ui/components/shared/CourseFilterWidget.tsx, app/imports/ui/components/shared/OpportunitySortWidget.tsx, app/imports/ui/pages/shared/CardExplorerOpportunitiesPage.tsx, app/imports/ui/pages/shared/FirstMenu.tsx
=> [issue-292] Polish UI of Card Explorer Opportunities

app/imports/startup/client/routes-config.ts, app/imports/ui/components/landing/LandingNavBar.tsx, app/imports/ui/components/landing/LandingSection3.tsx, app/imports/ui/pages/landing/LandingHomePage.tsx
* Now displays the logged in user role for the Home Button
* Minor typo fixes
Closes #302 
N/A
=> [issue-302] Polish UI of Landing

app/imports/ui/pages/onboard/andre/OnboardAndrePage.tsx, app/imports/ui/pages/onboard/andre/Task1Segment.tsx, app/imports/ui/pages/onboard/andre/Task2Segment.tsx, app/imports/ui/pages/onboard/andre/Task3Segment.tsx, app/imports/ui/pages/onboard/andre/Task4Segment.tsx, app/imports/ui/pages/onboard/andre/Task5Segment.tsx, app/imports/ui/pages/onboard/andre/Task6DescriptionEdit.tsx, app/imports/ui/pages/onboard/andre/Task6Segment.tsx, app/imports/ui/pages/onboard/andre/Task7Segment.tsx
This adds my finished sandbox page to Master.
Passed all tests on Windows.
=> issue-468-andre: Merging Completed Onboard Tasks

app/imports/ui/components/landing/ExplorerButtons.tsx, app/imports/ui/components/landing/explorer/LandingExplorerMenuBar.tsx, app/tests/landing.page.js, app/tests/simple.page.ts, app/tests/tests.admin.testcafe.ts
test-acceptance now tests the landing explorer pages and checks to see if they are displayed.
=> Issue 483 - Acceptance testing for landing explorer pages

app/imports/ui/pages/onboard/trey/OnboardTreyPage.tsx, app/imports/ui/pages/onboard/trey/Task1.tsx, app/imports/ui/pages/onboard/trey/Task2.tsx, app/imports/ui/pages/onboard/trey/Task3.tsx, app/imports/ui/pages/onboard/trey/Task4.tsx, app/imports/ui/pages/onboard/trey/Task5.tsx, app/imports/ui/pages/onboard/trey/Task6.tsx, app/imports/ui/pages/onboard/trey/Task7.tsx
Onboarding tasks are updated with suggested changes.
=> isssue-468-trey - Updated onboarding tasks

app/imports/ui/components/admin/AdminPageMenu.tsx, app/imports/ui/components/advisor/AdvisorPageMenu.tsx, app/imports/ui/components/faculty/FacultyPageMenu.tsx, app/imports/ui/components/landing/ExplorerButtons.tsx, app/imports/ui/components/landing/RadGradLoginButtons.tsx, app/imports/ui/components/landing/UserGuideButtons.tsx, app/imports/ui/components/landing/explorer/LandingExplorerMenuBar.tsx, app/imports/ui/components/shared/FirstMenu.tsx, app/imports/ui/pages/SigninPage.tsx, app/imports/ui/utilities/ComponentIDs.ts, app/tests/landing.page.js, app/tests/navbar.admin.component.js, app/tests/navbar.advisor.component.js, app/tests/navbar.faculty.component.js, app/tests/navbar.landing.component.js, app/tests/navbar.student.component.js, app/tests/signin.page.js
A utility file named ComponentIDs.ts which declares an exported enum named COMPONENTIDS that defines enum values for different component id's that are referenced in the testing files. 
Not all the enums are hard-coded values in component files so the enum only ends up being used in the testing files. Also, the admin visibility, forecast, and community page does not seem to be tested which might be another …
=> Issue 547 - Created COMPONENTSIDS enums

app/imports/ui/components/shared/explorer/item-view/ExplorerProfiles.tsx
<b>Pull Request Issue 529</b><br/>
Issue 529, added a show more and show less button for the list of students.
=> Issue 529: Show More and Show Less Button 

app/imports/api/course/CourseCollection.ts, app/imports/ui/components/admin/datamodel/course/AddCourseForm.tsx, app/imports/ui/components/admin/datamodel/course/UpdateCourseForm.tsx, app/imports/ui/components/landing/explorer/LandingExplorerCard.tsx, app/imports/ui/components/shared/explorer/browser-view/ExplorerCard.tsx, app/imports/ui/components/shared/manage/course/EditCourseButton.tsx, app/imports/ui/components/student/degree-planner/DetailCourseCard.tsx, app/imports/ui/components/student/degree-planner/ProfileCourseCard.tsx, app/imports/ui/components/student/reviews/utilities/review-name.ts, app/imports/ui/pages/admin/AdminDataModelCoursesPage.tsx, app/imports/ui/pages/landing/LandingCourseExplorerPage.tsx, app/imports/ui/pages/shared/item-view/CourseViewPage.tsx, app/private/database/development/2021-05-30-12-31-05.json
Implements a standard course name using CourseCollection.getName method.
=> Issue 560: Create CourseCollection.getName method and use the method.

app/imports/api/career/CareerGoalCollection.ts, app/imports/api/interest/InterestCollection.ts
Retire related teasers when we retire a CareerGoal or Interest
=> Issue 575 - Retire related teasers when we retire a CareerGoal or Interest

app/imports/ui/pages/landing/LandingCareerGoalExplorerPage.tsx, app/imports/ui/pages/landing/LandingCareerGoalsExplorerPage.tsx, app/imports/ui/pages/landing/LandingCourseExplorerPage.tsx, app/imports/ui/pages/landing/LandingCoursesExplorerPage.tsx, app/imports/ui/pages/landing/LandingHomePage.tsx, app/imports/ui/pages/landing/LandingInterestExplorerPage.tsx, app/imports/ui/pages/landing/LandingInterestsExplorerPage.tsx, app/imports/ui/pages/landing/LandingOpportunitiesExplorerPage.tsx, app/imports/ui/pages/landing/LandingOpportunityExplorerPage.tsx
Remove user-related collections and update header image links for the landing pages. 
=> Issue 579 - Landing page should not subscribe to user-related collections

app/imports/ui/components/student/degree-planner/RemoveIt.tsx, app/imports/ui/pages/admin/AdminAnalyticsNewsletterPage.tsx, app/imports/ui/pages/admin/AdminDataModelInterestsPage.tsx, app/imports/ui/pages/admin/AdminDataModelReviewsPage.tsx, app/imports/ui/pages/admin/AdminDataModelSlugsPage.tsx, archive/onboard/andre/Task6DescriptionEdit.tsx
Replaced reamining Swal alerts with RadGradAlert
Most of the Swals were in files that were rolled back due to the merge. The remaining Swals are from the onboard pages or is the consent alert that has only one instance of it.
=> Replaced remaining Swal alerts with RadGradAlert

app/imports/ui/pages/shared/item-view/CourseViewPage.tsx, app/imports/ui/pages/shared/item-view/OpportunityViewPage.tsx
Filter out Course and Opportunity reviews that has the visible property set false. 
=> Issue 583: Course and Opportunity item views show reviews that should be hidden.

app/imports/ui/pages/shared/HomePage.tsx
The user is now logged out after refusing the terms and conditions.
The way it is implemented is in sort of a "hacky" way and would be open to hearing alternatives or issues that may arise from how I implemented it.
=> Issue 540 - User is not immediately logged out after refusing terms and conditions

app/imports/ui/components/advisor/manage/AdvisorAddStudentTab.tsx, app/imports/ui/components/advisor/manage/AdvisorFilteredStudentTabs.tsx, app/imports/ui/components/advisor/manage/AdvisorManageStudents.tsx, app/imports/ui/components/advisor/manage/AdvisorOtherTab.tsx, app/imports/ui/components/advisor/manage/MatriculateStudentsTab.tsx, app/imports/ui/utilities/ComponentIDs.ts, app/tests/navbar.admin.component.js, app/tests/tests.admin.testcafe.ts
Created testcafe tests that ensure that the different tabs located on the manage student page load.
The tests are performed under the "Test admin management pages" test.
=> Issue 585 - TestCafe for ManageStudentPage

app/imports/ui/pages/shared/item-view/CourseViewPage.tsx
Prerequisite courses component on courses page is only displayed if there are prerequisites
=> Issue 621 - Prerequisite courses component only shown if there are any

app/imports/ui/components/advisor/manage/AdvisorAddStudentTab.tsx, app/imports/ui/components/advisor/manage/AdvisorFilterStudents.tsx, app/imports/ui/components/advisor/manage/ManageStudentItem.tsx, app/imports/ui/utilities/ComponentIDs.ts, app/tests/manage.pages.js, app/tests/navbar.admin.component.js, app/tests/tests.admin.testcafe.ts, app/tests/tests.advisor.testcafe.ts
All of the tabs on the manage students page when viewed by an advisor are visited, the ability to add a student is test, and the filter functionality is tested.
I created a new file called manage.pages.js to store the tests as the functions are also used in admin tests.
=> Issue 627 - Created test for advisor manage students page

app/imports/ui/components/shared/explorer/item-view/opportunity/ExplorerOpportunity.tsx
Fix markdown for opportunity description fields. 
=> Issue 636 - Fix rendering of Opportunity description fields

app/imports/ui/components/shared/button/ButtonAction.tsx, app/imports/ui/components/student/verification-requests/RequestVerificationPopup.tsx, app/imports/ui/utilities/ComponentIDs.ts, app/tests/manage.pages.js, app/tests/tests.student.testcafe.ts
Tests to ensure that a student can submit a request for verification after completing an opportunity.
I merged issue 624 into this branch as I touch similar files and wanted to address the merge conflicts.
=> Issue 625 - Testcafe test for Student Request Verification

app/imports/ui/components/shared/explorer/item-view/course/ExplorerCourse.tsx, app/imports/ui/components/shared/explorer/item-view/opportunity/ExplorerOpportunity.tsx, app/imports/ui/components/student/explorer/StudentExplorerReviewWidget.tsx
Improve Opportunity and Course Review and Student Participation components. Review components now have an icon and indicates if there is no reviews. Also, Student Participation components has an icon and is left-aligned. 
=> Issue 658 & 659 - Improve Opportunity and Course Review and Student Participation components

app/package.json, app/tests/*.testcafe.details.ts, app/tests/details.page.js
A separate script that can be run using the command `meteor npm run test-details` or `meteor npm run test-details-acceptance` which tests every details page for interests, career goals, courses, and opportunities.
=> Issue 664 - Special script to test every detail page

app/imports/ui/components/checklist/LevelChecklist.tsx
Message saying you have not achieved a new level in awhile no longer displays for level 6 students.
=> Issue 676 - Fix levels checklist item for level 6 students

app/imports/ui/components/shared/InterestList.tsx
Issue 693: The interest lists in the Explorer Card is Alphabetically ordered.
=> Issue 693: The List of Interests are Alphabetically Ordered

app/imports/ui/components/shared/explorer/browser-view/BrowserView.tsx, app/imports/ui/components/shared/explorer/browser-view/ExplorerCard.tsx
Sort By: Most Recent filter was fixed to show most recent based on either updatedAt or createdAt field. Explorer cards also display the last updated date.
=> Issue 683 - Fix Sort By: Most Recent

app/imports/ui/pages/admin/AdminAnalyticsBehaviorTablePage.tsx
Duplicate users aren't displayed on student behavior table, and num users column was changed to total interactions.
=> Issue 687 - Removed duplicate users

app/imports/ui/components/admin/datamodel/opportunity/AddOpportunityForm.tsx
Prevents pictureURL from resetting to nothing. Resets form after submission. 
=> Issue 685: Fixed OpportunityForm picturefield

app/imports/ui/components/shared/community/UpComingEventsCard.tsx, app/imports/ui/components/shared/community/UpComingEventsList.tsx, app/imports/ui/components/shared/community/UpcomingEvents.tsx
Revised Upcoming Events component. 
=> Issue 663 - Implement Upcoming Events component 

app/imports/ui/components/landing/RadGradLoginButtons.tsx
This replaced the wrapped button code to be replaced simply by a button attribute to the dropdown instead. This allows for the dropdown to be pressed on all dimensions of the button itself.
=> Fixed login button dimension problem

app/imports/ui/components/shared/explorer/browser-view/BrowserView.tsx, app/imports/ui/components/shared/explorer/browser-view/Search.tsx
A search bar was added to the explorer browser view pages
=> Issue 740 - Add search bar to explorer browser view
